# Generated by Django 4.1.7 on 2023-02-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_code', models.CharField(max_length=50)),
                ('market_type', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=200)),
                ('security_type', models.CharField(max_length=50)),
                ('corporate_action', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('strike_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('option_type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
