# Generated by Django 4.1.7 on 2023-02-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RF_Options_Chain_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_insertion', models.DateField(default=None)),
                ('option_code', models.CharField(default='', max_length=50)),
                ('option_type', models.CharField(max_length=50)),
                ('underlying_asset', models.CharField(max_length=50)),
                ('expiration_date', models.DateField(default=None)),
                ('strike_price', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
        ),
        migrations.DeleteModel(
            name='DataItem',
        ),
    ]
